"""How long must dosing continue before it can stop?

A question this project could not previously ask. `monotherapy_backtest` showed the engine had no
extinction state, so any finite course regrew from a residual of 1e-82 and every such analysis
returned zero. With the opt-in `extinction_threshold` in place the question becomes answerable, and
the answer contradicts a conclusion the frozen findings state as settled.

THE RESULT
Proposed two-agent regimen, local delivery (penetration 2.0), given for a fixed period and then
STOPPED. Ten-year relapse-free fraction, 300 trials, seed 7:

    dosing duration      1 cell @K=1e9    1 cell @K=1e12
    3 months                 0.000            0.000
    6 months                 0.000            0.000
    1 year                   0.000            0.000
    2 years                  0.380            0.380
    3 years                  0.993            0.993
    indefinite               1.000            1.000

Three years of dosing captures 99.3% of what indefinite dosing achieves. For a dog with eight to
ten years of life remaining that is the difference between a course of treatment and a life
sentence -- and it removes the cumulative irreversible hepatic exposure, the cost and the decade of
compliance that the indefinite-dosing assumption silently imposed.

WHY THIS IS MORE TRUSTWORTHY THAN MOST FIGURES HERE
The two carrying-capacity anchors give IDENTICAL results at every duration. That parameter was the
free one that had to be moved to make the lomustine back-test land near its target; here it does
not matter at all, so the result does not depend on it.

WHAT THE FIX IS WORTH, MEASURED
At two years the old engine returns 0.003 and the fixed engine returns 0.380. That is not a
refinement -- it is the difference between "stopping is hopeless" and "stopping works in more than
a third of dogs". The project's `DURATION_CAP_GENERALIZATION` and its 0.060/day drugs-off bar were
artifacts sitting on top of a real and findable answer.

WHY THREE YEARS RATHER THAN THREE MONTHS
The requirement is set by how long the regimen needs at net-negative growth to drive the tumour
from its post-surgical residual past one cell -- roughly sixteen e-foldings. At the modelled kill
rate that is a little over two years. It is not arbitrary, and it is directly improvable: a more
potent regimen shortens the course. That reframes potency from "does it work at all" into "how soon
can the dog stop", which is a more useful question than the one this project has been asking.

THE CAVEAT THAT MATTERS MOST
The cliff -- 0.000, then 0.380, then 0.993 -- is characteristic of a DETERMINISTIC threshold. Real
cell loss is stochastic: some animals clear early by luck and some do not, and it takes only one
fortunate trajectory. With proper stochastic clearance the curve would smooth and almost certainly
shift EARLIER, so three years is likely an overestimate of the required duration. By how much
cannot be said until stochastic loss is implemented.

AND ONE COINCIDENCE TO REFUSE
0.380 at two years is close to Skorupski's observed 0.375. Different drug, different setting,
different mechanism. It is not a second validation and must not be read as one.

WHAT THIS DOES NOT CHANGE
No dog has received any agent in this regimen. The clone growth rates underneath the e-folding
arithmetic are illustrative rather than fitted. This is a model output whose most important
property is that it CONTRADICTS the frozen findings, not that it confirms anything.
"""

from __future__ import annotations

TEN_YEAR_RELAPSE_FREE_BY_DOSING_DURATION = {
    # days of dosing -> {anchor: relapse-free at 10 years}
    90: {"one_cell_1e9": 0.000, "one_cell_1e12": 0.000},
    180: {"one_cell_1e9": 0.000, "one_cell_1e12": 0.000},
    365: {"one_cell_1e9": 0.000, "one_cell_1e12": 0.000},
    730: {"one_cell_1e9": 0.380, "one_cell_1e12": 0.380},
    1095: {"one_cell_1e9": 0.993, "one_cell_1e12": 0.993},
    None: {"one_cell_1e9": 1.000, "one_cell_1e12": 1.000},
}

WITHOUT_THE_EXTINCTION_STATE = {180: 0.000, 365: 0.000, 730: 0.003}

PRACTICAL_DOSING_DURATION_DAYS = 1095


def verdict() -> dict:
    return {
        "the_answer": "About three years, not forever. 1095 days of dosing gives 0.993 at ten "
                      "years against 1.000 for indefinite dosing -- 99.3% of the benefit for 30% "
                      "of the exposure.",
        "what_it_contradicts": "`FROZEN_FINDINGS.md` states the lung/no-antigen regimen is never "
            "stoppable and quotes a 0.060/day drugs-off bar with no candidate mechanism. Both were "
            "generated by an engine that could not represent a cured animal. The bar was measuring "
            "the wrong thing: it asked what immune rate could hold the line against a tumour that "
            "regrows from any residual, when the residual can simply be eliminated.",
        "the_knock_on_effect": "The ten-year endurance analysis -- tolerability headroom, the "
            "0.045/day antigen-independent immune requirement, the SOD1 concern about repeated "
            "intrathecal dosing -- exists to solve 'how does a dog tolerate a decade of drugs'. At "
            "a three-year course each of those shrinks or disappears. The immune arm may not be "
            "needed for ENDURANCE at all, though the persister argument for it is untouched, being "
            "mechanistic rather than a durability computation.",
        "robustness": "The two carrying-capacity anchors agree exactly at every duration, so the "
                      "result does not rest on the free parameter that the lomustine fit did.",
        "the_direction_of_the_remaining_error": "Favourable. A deterministic threshold understates "
            "clearance because it cannot let a lucky trajectory clear early, so the true required "
            "duration is probably shorter than three years.",
        "what_would_settle_it": "Stochastic cell loss at low burden, replacing the hard threshold. "
                                "Until then the shape of the curve is an artifact of the "
                                "implementation even though its direction is not.",
    }


# ---------------------------------------------------------------------------------------------
# Where the ten-year figure actually comes from, and what potency does (and does not) buy.
# ---------------------------------------------------------------------------------------------

# 10-year relapse-free, one structural change at a time. Steps 0->1 and 3->4 are clean
# single-variable comparisons; step 2 uses a different scenario so the ladder is not a single sweep
# throughout.
ABLATION_FROM_WHAT_WAS_TRIED = {
    "0_chemo_finite_course": 0.000,
    "1_plus_remove_the_duration_cap": 1.000,
    "2_plus_driver_targeted_agent": 0.693,
    "3_plus_second_agent_independent_axis": 0.993,
    "4_plus_local_delivery_past_the_barrier": 1.000,
    "single_agent_only_at_pen_2_0": 0.977,
    "THE_UNCOMFORTABLE_FINDING": "Steps 0->1 is the one clean single-variable comparison -- same "
        "model, same drug, only the exposure cap removed -- and it goes from 0.000 to 1.000. That "
        "single change accounts for the entire gap between 'several hundred days' and the ten-year "
        "figure. Everything after it is refinement on a number already at ceiling: the second agent "
        "adds 0.023 over a single agent, local delivery adds 0.007 over systemic.",
    "why_that_is_a_problem_and_not_a_result": "Continuous dosing is EXACTLY the axis the engine was "
        "shown to handle incorrectly. A model with no extinction state cannot credit a finite course "
        "with anything, so it assigns the whole benefit to 'never stop'. The ablation therefore "
        "cannot distinguish (a) continuous targeted therapy genuinely being transformative here from "
        "(b) the engine rewarding indefinite dosing by construction while the real value of the "
        "targeted agents and local delivery hides under a saturated ceiling.",
}

# Finite-course durability vs ERK inhibitor potency, extinction ON, penetration 2.0.
# scale is a multiplier on the modelled IC50 of 300 nM.
POTENCY_DOES_NOT_SHORTEN_THE_COURSE = {
    # stop_day -> {modelled 300nM, ~27nM est. cellular, ~5nM biochemical}
    180: (0.000, 0.000, 0.000),
    365: (0.000, 0.000, 0.000),
    547: (0.017, 0.073, 0.080),
    730: (0.380, 0.830, 0.830),
    1095: (0.993, 1.000, 1.000),
    "what_the_columns_are": "Temuterkib's biochemical IC50 is 5 nM; this repo's own Cheng-Prusoff "
        "cellular estimate is ~27 nM median. The model assumes 300 nM, an acknowledged placeholder.",
    "an_11x_potency_gain_helps_at_two_years": "0.380 -> 0.830. Real, and it matters: the difference "
        "between a third of dogs staying clear after stopping at two years and most of them.",
    "BUT_IT_DOES_NOT_SHORTEN_THE_REQUIRED_COURSE": "18 months remains ~0.08 and 2-3 years is still "
        "needed. And 27 nM vs 5 nM is a difference of nothing at the durations that decide the "
        "answer -- identical at 2 and 3 years, and 0.073 vs 0.080 at 18 months, inside Monte Carlo "
        "noise at 300 trials. At a steady state of 500 nM an IC50 of 27 nM is already 18x below "
        "it, so the Emax term is essentially saturated and further affinity buys nothing that "
        "matters. An earlier guess that a tenfold more potent ERK agent would substantially "
        "shorten the course was WRONG.",
    "WHAT_ACTUALLY_BINDS": "max_kill -- the kill ceiling, 0.18/day -- not IC50 and not "
        "concentration. And max_kill is the parameter the provenance audit flagged as 'pinned by "
        "solving backwards from recorded margins': the least defensible input in the model. So the "
        "finite-course result, the most clinically useful thing here, rests almost entirely on the "
        "one number with no evidence behind it. Measuring a real ERK-inhibitor kill ceiling against "
        "canine HS cells would move the three-year figure more than any pharmacology improvement, "
        "and it is a straightforward in-vitro experiment.",
}
